// Don't look at me like that, I know
// this is a PoC

export type Acronym = {
    name: string;
    class: string;
    fullName: string;
    weaponName: string;
    type: string;
};

export default [
    { name: 'LT', class: 'Driller', fullName: 'Lighter Tanks', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'SA', class: 'Driller', fullName: 'Sticky Additive', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'CFV', class: 'Driller', fullName: 'Compact Feed Valves', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'FSD', class: 'Driller', fullName: 'Fuel Stream Diffuser', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'SF', class: 'Driller', fullName: 'Sticky Fuel', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'FM', class: 'Driller', fullName: 'Facemelter', weaponName: 'CRSPR Flamethrower', type: 'Overclock' },
    { name: 'ITE', class: 'Driller', fullName: 'Improved Thermal Efficiency', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'TC', class: 'Driller', fullName: 'Tuned Cooler', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'IS', class: 'Driller', fullName: 'Ice Storm', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'FRE', class: 'Driller', fullName: 'Flow Rate Expansion', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'SB', class: 'Driller', fullName: 'Snowball', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'IS', class: 'Driller', fullName: 'Ice Spear', weaponName: 'Cryo Cannon', type: 'Overclock' },
    { name: 'AG', class: 'Driller', fullName: 'AG Mixture', weaponName: '', type: 'Overclock' },
    { name: 'DC', class: 'Driller', fullName: 'Disperser Compound', weaponName: 'Corrosive Sludge Pump', type: 'Overclock' },
    { name: 'GBS', class: 'Driller', fullName: 'Goo Bomber Special', weaponName: 'Corrosive Sludge Pump', type: 'Overclock' },
    { name: 'HIA', class: 'Driller', fullName: 'Hydrogen Ion Additive', weaponName: 'Corrosive Sludge Pump', type: 'Overclock' },
    { name: 'VIM', class: 'Driller', fullName: 'Volatile Impact Mixture', weaponName: 'Corrosive Sludge Pump', type: 'Overclock' },
    { name: 'SB', class: 'Driller', fullName: 'Sludge Blast', weaponName: 'Corrosive Sludge Pump', type: 'Overclock' },
    { name: 'CH', class: 'Driller', fullName: 'Chain Hit', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'OM', class: 'Driller', fullName: 'Oversized Magazine', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'AF', class: 'Driller', fullName: 'Automatic Fire', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'HP', class: 'Driller', fullName: 'Homebrew Powder', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'ER', class: 'Driller', fullName: 'Explosive Reload', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'TR', class: 'Driller', fullName: 'Tranquilizer Rounds', weaponName: 'Subata 120', type: 'Overclock' },
    { name: 'ER', class: 'Driller', fullName: 'Energy Rerouting', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'HP', class: 'Driller', fullName: 'Heat Pipe', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'OC', class: 'Driller', fullName: 'Overcharger', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'MCU', class: 'Driller', fullName: 'Magnetic Cooling Unit', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'HH', class: 'Driller', fullName: 'Heavy Hitter', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'PP', class: 'Driller', fullName: 'Persistent Plasma', weaponName: 'Experimental Plasma Charger', type: 'Overclock' },
    { name: 'LCS', class: 'Driller', fullName: 'Liquid Cooling System', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'DR', class: 'Driller', fullName: 'Diffusion Ray', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'BN', class: 'Driller', fullName: 'Blistering Necrosis', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'SFL', class: 'Driller', fullName: 'Super Focus Lens', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'MPS', class: 'Driller', fullName: 'Mega Power Supply', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'GC', class: 'Driller', fullName: 'Gamma Contamination', weaponName: 'Colette Wave Cooker', type: 'Overclock' },
    { name: 'ST', class: 'Engineer', fullName: 'Stunner', weaponName: '"Warthog" Auto 210', type: 'Overclock' },
    { name: 'MPA', class: 'Engineer', fullName: 'Magnetic Pellet Alignment', weaponName: '"Warthog" Auto 210', type: 'Overclock' },
    { name: 'CO', class: 'Engineer', fullName: 'Cycle Overload', weaponName: '"Warthog" Auto 210', type: 'Overclock' },
    { name: 'LWM', class: 'Engineer', fullName: 'Light-Weight Magazines', weaponName: '"Warthog" Auto 210', type: 'Overclock' },
    { name: 'MS', class: 'Engineer', fullName: 'Mini Shells', weaponName: '"Warthog" Auto 210', type: 'Overclock' },
    { name: 'SSR', class: 'Engineer', fullName: 'Super-Slim Rounds', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'EMRB', class: 'Engineer', fullName: 'EM Refire Booster', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'TA', class: 'Engineer', fullName: 'Turret Arc', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'WOM', class: 'Engineer', fullName: 'Well Oiled Machine', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'LWR', class: 'Engineer', fullName: 'Light-Weight Rounds', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'TEMD', class: 'Engineer', fullName: 'Turret EM Discharge', weaponName: '"Stubby" Voltaic SMG', type: 'Overclock' },
    { name: 'ABM', class: 'Engineer', fullName: 'Armor Break Module', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'ECR', class: 'Engineer', fullName: 'Explosive Chemical Rounds', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'EXEC', class: 'Engineer', fullName: 'Executioner', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'ER', class: 'Engineer', fullName: 'Eraser', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'SR', class: 'Engineer', fullName: 'Seeker Rounds', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'NL', class: 'Engineer', fullName: 'Neuro-Lasso', weaponName: 'LOK-1 Smart Rifle', type: 'Overclock' },
    { name: 'CS', class: 'Engineer', fullName: 'Clean Sweep', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'CR', class: 'Engineer', fullName: 'Compact Rounds', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'FB', class: 'Engineer', fullName: 'Fat Boy', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'PR', class: 'Engineer', fullName: 'Pack Rat', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'RJ', class: 'Engineer', fullName: 'RJ250 Compound', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'HP', class: 'Engineer', fullName: 'Hyper Propellant', weaponName: 'Deepcore 40mm PGL', type: 'Overclock' },
    { name: 'LWC', class: 'Engineer', fullName: 'Light-Weight Cases', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'RTS', class: 'Engineer', fullName: 'Return to Sender', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'SD', class: 'Engineer', fullName: 'Spinning Death', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'RC', class: 'Engineer', fullName: 'Roll Control', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'HVC', class: 'Engineer', fullName: 'High Voltage Crossover', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'IF', class: 'Engineer', fullName: 'Inferno', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'SPC', class: 'Engineer', fullName: 'Stronger Plasma Current', weaponName: 'Breach Cutter', type: 'Overclock' },
    { name: 'ET', class: 'Engineer', fullName: 'Efficiency Tweaks', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'ABC', class: 'Engineer', fullName: 'Automated Beam Controller', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'PC', class: 'Engineer', fullName: 'Plastcrete Catalyst', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'FL', class: 'Engineer', fullName: 'Feedback Loop', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'ODB', class: 'Engineer', fullName: 'Overdrive Booster', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'VIR', class: 'Engineer', fullName: 'Volatile Impact Reactor', weaponName: 'Shard Diffractor', type: 'Overclock' },
    { name: 'ALMO', class: 'Gunner', fullName: 'A Little More Oomph!', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'BH', class: 'Gunner', fullName: 'Burning Hell', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'BH', class: 'Gunner', fullName: 'Bullet Hell', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'TDW', class: 'Gunner', fullName: 'Thinned Drum Walls', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'CFM', class: 'Gunner', fullName: 'Compact Feed Mechanism', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'LS', class: 'Gunner', fullName: 'Lead Storm', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'EV', class: 'Gunner', fullName: 'Exhaust Vectoring', weaponName: '"Lead Storm" Powered Minigun', type: 'Overclock' },
    { name: 'CD', class: 'Gunner', fullName: 'Composite Drums', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'CB', class: 'Gunner', fullName: 'Carpet Bomber', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'BB', class: 'Gunner', fullName: 'Big Bertha', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'SS', class: 'Gunner', fullName: 'Splintering Shells', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'CM', class: 'Gunner', fullName: 'Combat Mobility', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'NTP', class: 'Gunner', fullName: 'Neurotoxin Payload', weaponName: '"Thunderhead" Heavy Autocannon', type: 'Overclock' },
    { name: 'OFM', class: 'Gunner', fullName: 'Overtuned Feed Mechanism', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'PBM', class: 'Gunner', fullName: 'Plasma Burster Missiles', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'JFH', class: 'Gunner', fullName: 'Jet Fuel Homebrew', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'FM', class: 'Gunner', fullName: 'Fragmentation Missiles', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'MS', class: 'Gunner', fullName: 'Minelayer System', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'SM', class: 'Gunner', fullName: 'Salvo Module', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'RB', class: 'Gunner', fullName: 'Rocket Barrage', weaponName: '"Hurricane" Guided Rocket System', type: 'Overclock' },
    { name: 'CH', class: 'Gunner', fullName: 'Chain Hit', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'HP', class: 'Gunner', fullName: 'Homebrew Powder', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'ER', class: 'Gunner', fullName: 'Elephant Rounds', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'VB', class: 'Gunner', fullName: 'Volatile Bullets', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'MB', class: 'Gunner', fullName: 'Magic Bullets', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'SS', class: 'Gunner', fullName: 'Six Shooter', weaponName: '"Bulldog" Heavy Revolver', type: 'Overclock' },
    { name: 'CC', class: 'Gunner', fullName: 'Composite Casings', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'CM', class: 'Gunner', fullName: 'Compact Mags', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'EM', class: 'Gunner', fullName: 'Electro Minelets', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'FCS', class: 'Gunner', fullName: 'Full Chamber Seal', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'ER', class: 'Gunner', fullName: 'Experimental Rounds', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'MF', class: 'Gunner', fullName: 'Micro Flechettes', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'LS', class: 'Gunner', fullName: 'Lead Spray', weaponName: 'BRT7 Burst Fire Gun', type: 'Overclock' },
    { name: 'UMC', class: 'Gunner', fullName: 'Ultra-Magnetic Coils', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'BFM', class: 'Gunner', fullName: 'Backfeeding Module', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'HF', class: 'Gunner', fullName: 'Hellfire', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'RA', class: 'Gunner', fullName: 'Re-Atomizer', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'TM', class: 'Gunner', fullName: 'The Mole', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'TTC', class: 'Gunner', fullName: 'Triple-Tech Chambers', weaponName: 'ArmsKore Coil Gun', type: 'Overclock' },
    { name: 'CA', class: 'Gunner', fullName: 'Compact Ammo', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'OFM', class: 'Scout', fullName: 'Overclocked Firing Mechanism', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'AISE', class: 'Scout', fullName: 'AI Stability Engine', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'GR', class: 'Scout', fullName: 'Gas Rerouting', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'BOM', class: 'Scout', fullName: 'Bullets of Mercy', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'ER', class: 'Scout', fullName: 'Electrifying Reload', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'HP', class: 'Scout', fullName: 'Homebrew Powder', weaponName: 'Deepcore GK2', type: 'Overclock' },
    { name: 'HC', class: 'Scout', fullName: 'Hoverclock', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'ASS', class: 'Scout', fullName: 'Active Stability System', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'EFS', class: 'Scout', fullName: 'Electrocuting Focus Shots', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'MC', class: 'Scout', fullName: 'Minimal Clips', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'HIP', class: 'Scout', fullName: 'Hipster', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'SCC', class: 'Scout', fullName: 'Supercooling Chamber', weaponName: 'M1000 Classic', type: 'Overclock' },
    { name: 'TLC', class: 'Scout', fullName: 'Thermal Liquid Coolant', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'RWM', class: 'Scout', fullName: 'Rewiring Mod', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'OPA', class: 'Scout', fullName: 'Overtuned Particle Accelerator', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'AV', class: 'Scout', fullName: 'Aggressive Venting', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'ID', class: 'Scout', fullName: 'Impact Deflection', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'SBB', class: 'Scout', fullName: 'Shield Battery Booster', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'TEF', class: 'Scout', fullName: 'Thermal Exhaust Feedback', weaponName: 'DRAK-25 Plasma Carbine', type: 'Overclock' },
    { name: 'CS', class: 'Scout', fullName: 'Compact Shells', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'SS', class: 'Scout', fullName: 'Shaped Shells', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'JS', class: 'Scout', fullName: 'Jumbo Shells', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'SP', class: 'Scout', fullName: 'Special Powder', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'DB', class: 'Scout', fullName: 'Double Barrel', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'SS', class: 'Scout', fullName: 'Stuffed Shells', weaponName: 'Jury-Rigged Boomstick', type: 'Overclock' },
    { name: 'MM', class: 'Scout', fullName: 'Minimal Magazines', weaponName: 'Zhukov NUK17', type: 'Overclock' },
    { name: 'CC', class: 'Scout', fullName: 'Custom Casings', weaponName: 'Zhukov NUK17', type: 'Overclock' },
    { name: 'CM', class: 'Scout', fullName: 'Cryo Minelets', weaponName: 'Zhukov NUK17', type: 'Overclock' },
    { name: 'ED', class: 'Scout', fullName: 'Embedded Detonators', weaponName: 'Zhukov NUK17', type: 'Overclock' },
    { name: 'GR', class: 'Scout', fullName: 'Gas Recycling', weaponName: 'Zhukov NUK17', type: 'Overclock' },
    { name: 'QF', class: 'Scout', fullName: 'Quick Fire', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
    { name: 'CB', class: 'Scout', fullName: 'Cryo Bolts', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
    { name: 'BP', class: 'Scout', fullName: 'Bodkin Points', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
    { name: 'TS', class: 'Scout', fullName: 'The Specialist', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
    { name: 'FB', class: 'Scout', fullName: 'Fire Bolts', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
    { name: 'TV', class: 'Scout', fullName: 'Trifork Volley', weaponName: 'Nishanka Boltshark X-80', type: 'Overclock' },
] as Acronym[];