-- WARNING! do not insert this into prod database as it, there is no safeguards against data duplication because of
-- serial primary ID on some tables
-- this is kept here until fixed

-- insert DRG overclocks into acronyms table
INSERT INTO public.acronyms (acronym, acronym_type, guild_id, payload)
VALUES
    ('LT', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Lighter Tanks"}'),
    ('SA', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Sticky Additive"}'),
    ('CM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Compact Mags"}'),
    ('EM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Electro Minelets"}'),
    ('FCS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Full Chamber Seal"}'),
    ('CFV', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Compact Feed Valves"}'),
    ('FSD', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Fuel Stream Diffuser"}'),
    ('SF', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Sticky Fuel"}'),
    ('FM', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "CRSPR Flamethrower", "overclockName": "Facemelter"}'),
    ('ITE', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Improved Thermal Efficiency"}'),
    ('TC', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Tuned Cooler"}'),
    ('IS', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Ice Storm"}'),
    ('FRE', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Flow Rate Expansion"}'),
    ('SB', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Snowball"}'),
    ('IS', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Cryo Cannon", "overclockName": "Ice Spear"}'),
    ('DC', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "Disperser Compound"}'),
    ('GBS', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "Goo Bomber Special"}'),
    ('HIA', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "Hydrogen Ion Additive"}'),
    ('VIM', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "Volatile Impact Mixture"}'),
    ('SB', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "Sludge Blast"}'),
    ('CH', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Chain Hit"}'),
    ('OM', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Oversized Magazine"}'),
    ('AF', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Automatic Fire"}'),
    ('HP', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Homebrew Powder"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Explosive Reload"}'),
    ('TR', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Subata 120", "overclockName": "Tranquilizer Rounds"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Energy Rerouting"}'),
    ('HP', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Heat Pipe"}'),
    ('OC', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Overcharger"}'),
    ('MCU', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Magnetic Cooling Unit"}'),
    ('HH', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Heavy Hitter"}'),
    ('PP', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Experimental Plasma Charger", "overclockName": "Persistent Plasma"}'),
    ('LCS', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Liquid Cooling System"}'),
    ('DR', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Diffusion Ray"}'),
    ('BN', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Blistering Necrosis"}'),
    ('SFL', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Super Focus Lens"}'),
    ('MPS', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Mega Power Supply"}'),
    ('GC', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Colette Wave Cooker", "overclockName": "Gamma Contamination"}'),
    ('ST', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Warthog\" Auto 210", "overclockName": "Stunner"}'),
    ('MPA', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Warthog\" Auto 210", "overclockName": "Magnetic Pellet Alignment"}'),
    ('CO', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Warthog\" Auto 210", "overclockName": "Cycle Overload"}'),
    ('LWM', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Warthog\" Auto 210", "overclockName": "Light-Weight Magazines"}'),
    ('MS', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Warthog\" Auto 210", "overclockName": "Mini Shells"}'),
    ('SSR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Super-Slim Rounds"}'),
    ('EMRB', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "EM Refire Booster"}'),
    ('EMR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "EM Refire Booster"}'),
    ('TA', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Turret Arc"}'),
    ('WOM', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Well Oiled Machine"}'),
    ('LWR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Light-Weight Rounds"}'),
    ('TEMD', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Turret EM Discharge"}'),
    ('EMD', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "\"Stubby\" Voltaic SMG", "overclockName": "Turret EM Discharge"}'),
    ('ABM', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Armor Break Module"}'),
    ('ECR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Explosive Chemical Rounds"}'),
    ('AG', 'drg-overclock', '878318716801155233', '{"class": "Driller", "weaponName": "Corrosive Sludge Pump", "overclockName": "AG Mixture"}'),
    ('EXEC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Executioner"}'),
    ('EXE', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Executioner"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Eraser"}'),
    ('SR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Seeker Rounds"}'),
    ('NL', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "LOK-1 Smart Rifle", "overclockName": "Neuro-Lasso"}'),
    ('CS', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "Clean Sweep"}'),
    ('CR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "Compact Rounds"}'),
    ('FB', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "Fat Boy"}'),
    ('PR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "Pack Rat"}'),
    ('RJ', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "RJ250 Compound"}'),
    ('HP', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Deepcore 40mm PGL", "overclockName": "Hyper Propellant"}'),
    ('LWC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Light-Weight Cases"}'),
    ('RTS', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Return to Sender"}'),
    ('SD', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Spinning Death"}'),
    ('RC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Roll Control"}'),
    ('HVC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "High Voltage Crossover"}'),
    ('IF', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Inferno"}'),
    ('SPC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Breach Cutter", "overclockName": "Stronger Plasma Current"}'),
    ('ET', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Efficiency Tweaks"}'),
    ('ABC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Automated Beam Controller"}'),
    ('PC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Plastcrete Catalyst"}'),
    ('PCC', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Plastcrete Catalyst"}'),
    ('FL', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Feedback Loop"}'),
    ('ODB', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Overdrive Booster"}'),
    ('VIR', 'drg-overclock', '878318716801155233', '{"class": "Engineer", "weaponName": "Shard Diffractor", "overclockName": "Volatile Impact Reactor"}'),
    ('ALMO', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "A Little More Oomph!"}'),
    ('BH', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Burning Hell"}'),
    ('BH', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Bullet Hell"}'),
    ('TDW', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Thinned Drum Walls"}'),
    ('CFM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Compact Feed Mechanism"}'),
    ('LS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Lead Storm"}'),
    ('EV', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Lead Storm\" Powered Minigun", "overclockName": "Exhaust Vectoring"}'),
    ('CD', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Composite Drums"}'),
    ('CB', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Carpet Bomber"}'),
    ('BB', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Big Bertha"}'),
    ('SS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Splintering Shells"}'),
    ('CM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Combat Mobility"}'),
    ('NTP', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Thunderhead\" Heavy Autocannon", "overclockName": "Neurotoxin Payload"}'),
    ('OFM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Overtuned Feed Mechanism"}'),
    ('PBM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Plasma Burster Missiles"}'),
    ('JFH', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Jet Fuel Homebrew"}'),
    ('MM', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Zhukov NUK17", "overclockName": "Minimal Magazines"}'),
    ('FM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Fragmentation Missiles"}'),
    ('MS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Minelayer System"}'),
    ('SM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Salvo Module"}'),
    ('RB', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Hurricane\" Guided Rocket System", "overclockName": "Rocket Barrage"}'),
    ('CH', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Chain Hit"}'),
    ('HP', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Homebrew Powder"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Elephant Rounds"}'),
    ('VB', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Volatile Bullets"}'),
    ('MB', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Magic Bullets"}'),
    ('SS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "\"Bulldog\" Heavy Revolver", "overclockName": "Six Shooter"}'),
    ('CC', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Composite Casings"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Experimental Rounds"}'),
    ('MF', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Micro Flechettes"}'),
    ('LS', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "BRT7 Burst Fire Gun", "overclockName": "Lead Spray"}'),
    ('UMC', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "Ultra-Magnetic Coils"}'),
    ('BFM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "Backfeeding Module"}'),
    ('HF', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "Hellfire"}'),
    ('RA', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "Re-Atomizer"}'),
    ('TM', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "The Mole"}'),
    ('TTC', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "ArmsKore Coil Gun", "overclockName": "Triple-Tech Chambers"}'),
    ('CA', 'drg-overclock', '878318716801155233', '{"class": "Gunner", "weaponName": "Deepcore GK2", "overclockName": "Compact Ammo"}'),
    ('OFM', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "Overclocked Firing Mechanism"}'),
    ('AISE', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "AI Stability Engine"}'),
    ('GR', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "Gas Rerouting"}'),
    ('BOM', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "Bullets of Mercy"}'),
    ('ER', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "Electrifying Reload"}'),
    ('HP', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Deepcore GK2", "overclockName": "Homebrew Powder"}'),
    ('HC', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Hoverclock"}'),
    ('ASS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Active Stability System"}'),
    ('EFS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Electrocuting Focus Shots"}'),
    ('MC', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Minimal Clips"}'),
    ('HIP', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Hipster"}'),
    ('SCC', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "M1000 Classic", "overclockName": "Supercooling Chamber"}'),
    ('TLC', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Thermal Liquid Coolant"}'),
    ('RWM', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Rewiring Mod"}'),
    ('OPA', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Overtuned Particle Accelerator"}'),
    ('AV', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Aggressive Venting"}'),
    ('ID', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Impact Deflection"}'),
    ('SBB', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Shield Battery Booster"}'),
    ('TEF', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "DRAK-25 Plasma Carbine", "overclockName": "Thermal Exhaust Feedback"}'),
    ('CS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Compact Shells"}'),
    ('SS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Shaped Shells"}'),
    ('SHSH', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Shaped Shells"}'),
    ('JS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Jumbo Shells"}'),
    ('SP', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Special Powder"}'),
    ('DB', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Double Barrel"}'),
    ('SS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Jury-Rigged Boomstick", "overclockName": "Stuffed Shells"}'),
    ('CC', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Zhukov NUK17", "overclockName": "Custom Casings"}'),
    ('CM', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Zhukov NUK17", "overclockName": "Cryo Minelets"}'),
    ('ED', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Zhukov NUK17", "overclockName": "Embedded Detonators"}'),
    ('GR', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Zhukov NUK17", "overclockName": "Gas Recycling"}'),
    ('QF', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "Quick Fire"}'),
    ('CB', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "Cryo Bolts"}'),
    ('BP', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "Bodkin Points"}'),
    ('TS', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "The Specialist"}'),
    ('FB', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "Fire Bolts"}'),
    ('TV', 'drg-overclock', '878318716801155233', '{"class": "Scout", "weaponName": "Nishanka Boltshark X-80", "overclockName": "Trifork Volley"}');

-- insert DRG weapon mods (for Engineer and Driller) into acronyms table
INSERT INTO public.acronyms (guild_id, acronym, acronym_type, payload)
VALUES
    ('878318716801155233', 'HCT', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "High Capacity Tanks", "position": "A", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'HPE', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "High Pressure Ejector", "position": "B", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'UF', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Unfiltered Fuel", "position": "A", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'TFF', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Triple Filtered Fuel", "position": "B", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'SFD', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Sticky Flame Duration", "position": "C", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'OV', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Oversized Valves", "position": "A", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'SFS', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Sticky Flame Slowdown", "position": "B", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'MF', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "More Fuel", "position": "C", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'IB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "It Burns!", "position": "A", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'SFD', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Sticky Flame Duration", "position": "B", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'MF', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "More Fuel", "position": "C", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'HR', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Heat Radiance", "position": "A", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'TE', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Targets Explode", "position": "B", "weaponName": "CRSPR Flamethrower"}'),
    ('878318716801155233', 'LPC', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Larger Pressure Chamber", "position": "A", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'FTS', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Faster Turbine Spinup", "position": "B", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'SCU', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Stronger Cooling Unit", "position": "C", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'LRT', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Larger Reserve Tank", "position": "A", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'OET', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Overclocked Ejection Turbine", "position": "B", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'BIC', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Bypassed Integrity Check", "position": "C", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'IP', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Improved Pump", "position": "A", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'IFV', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Increased Flow Volume", "position": "B", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'HM', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Hard Mixture", "position": "A", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'SM', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Supercooling Mixture", "position": "B", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'LRT', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Larger Reserve Tank", "position": "C", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'Fragile', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Fragile", "position": "A", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'CR', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Cold Radiance", "position": "B", "weaponName": "Cryo Cannon"}'),
    ('878318716801155233', 'HCT', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "High Capacity Tanks", "position": "A", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'BAP', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Better Air Pressurizer", "position": "B", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'ASC', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Air Sensitive Compound", "position": "C", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'DN', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Dyse Nozzle", "position": "A", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'AN', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Atomizer Nozzle", "position": "B", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'PGM', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Potent Goo Mix", "position": "C", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'Supersaturation', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Supersaturation", "position": "A", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'MGC', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "More Goo Canisters", "position": "B", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'SE', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Spillback Extension", "position": "A", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'ISM', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Improved Spooling Mechanism", "position": "B", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'PDM', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Protein Disruption Mix", "position": "A", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'FA', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Fluoroantimonic Acid", "position": "B", "weaponName": "Corrosive Sludge Pump"}'),
    ('878318716801155233', 'IA', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Improved Alignment", "position": "A", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'HCM', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "High Capacity Magazine", "position": "B", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'IP', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Improved Propellant", "position": "B", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'RC', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Recoil Compensator", "position": "A", "weaponName": "Subata 120"}'),
    ('878318716801155233', '2RB', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "2-Round Burst", "position": "B", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'QE', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Quickfire Ejector", "position": "C", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'HPB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Hollow-Point Bullets", "position": "A", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'HVR', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "High Velocity Rounds", "position": "B", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Expanded Ammo Bags", "position": "C", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'VB', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Volatile Bullets", "position": "A", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'BR', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Blowthrough Rounds", "position": "B", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'NCTC', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Neuro-Corrosive Toxic Catalyst", "position": "C", "weaponName": "Subata 120"}'),
    ('878318716801155233', 'IPD', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Increased Particle Density", "position": "A", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'LB', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Larger Battery", "position": "B", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'HCPE', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Higher Charged Plasma Energy", "position": "C", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'HS', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Heat Shield", "position": "A", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'OPA', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Overcharged Plasma Accelerator", "position": "B", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'ICE', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Improved Charge Efficiency", "position": "A", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'CC', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Crystal Capacitors", "position": "B", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'TR', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Tweaked Radiator", "position": "C", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'EPS', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Expanded Plasma Splash", "position": "A", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'HDB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "High Density Battery", "position": "B", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'RS', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Reactive Shockwave", "position": "C", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'BN', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Burning Nightmare", "position": "A", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'TCF', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Thin Containment Field", "position": "B", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'PS', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Plasma Splash", "position": "C", "weaponName": "Experimental Plasma Charger"}'),
    ('878318716801155233', 'CL', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Convex Lens", "position": "A", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'MT', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Magnetron Tube", "position": "B", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'CL', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Concave Lens", "position": "C", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'HS', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Heat Sink", "position": "A", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'LPS', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Larger Power Supply", "position": "B", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'TC', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Thermoelectric Cooler", "position": "C", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'DR', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Densification Ray", "position": "A", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'TA', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Temperature Amplifier", "position": "B", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'WLAO', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Wide Lens Add-on", "position": "A", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'PSO', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Power Supply Overdrive", "position": "B", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'CT', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Contagion Transmitter", "position": "A", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'BR', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Boiler Ray", "position": "B", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'ER', 'drg-weapon-mod', '{"tier": "5", "class": "Driller", "modName": "Exothermic Reactor", "position": "C", "weaponName": "Colette Wave Cooker"}'),
    ('878318716801155233', 'BD', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Barbed Drills", "position": "A", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'HDT', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Hardened Drill Tips", "position": "B", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'EFT', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Expanded Fuel Tanks", "position": "C", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'MR', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Magnetic Refrigeration", "position": "A", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'SIC', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Streamlined Integrity Check", "position": "B", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'SM', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Supercharged Motor", "position": "A", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'ITP', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Increased Tank Pressure", "position": "A", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'BCD', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Bloody Cold Drills", "position": "B", "weaponName": "Reinforced Power Drills"}'),
    ('878318716801155233', 'FS', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Fragmentary Shell", "position": "A", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'ESC', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Extra Satchel Charge", "position": "B", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'BC', 'drg-weapon-mod', '{"tier": "1", "class": "Driller", "modName": "Bigger Charge", "position": "C", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'KS', 'drg-weapon-mod', '{"tier": "2", "class": "Driller", "modName": "Kill Switch", "position": "A", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'ESC', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Extra Satchel Charge", "position": "A", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'VC', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Volatile Compound", "position": "B", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'BB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Big Bang", "position": "A", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'CB', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Concussive Blast", "position": "B", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'RM', 'drg-weapon-mod', '{"tier": "4", "class": "Driller", "modName": "Rock Mover", "position": "C", "weaponName": "Satchel Charge"}'),
    ('878318716801155233', 'TI', 'drg-weapon-mod', '{"tier": "3", "class": "Driller", "modName": "Temperature Insulation", "position": "A", "weaponName": "Driller''s Armor"}'),
    ('878318716801155233', 'SFM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Supercharged Feed Mechanism", "position": "A", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'OM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Overstuffed Magazine", "position": "B", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'LS', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Loaded Shells", "position": "B", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'Choke', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Choke", "position": "C", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'RD', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Recoil Dampener", "position": "A", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'QE', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Quickfire Ejector", "position": "B", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'HCM', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "High Capacity Magazine", "position": "C", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'TCB', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Tungsten Coated Buckshot", "position": "A", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'BP', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Bigger Pellets", "position": "B", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'TW', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Turret Whip", "position": "A", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'MA', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Miner Adjustments", "position": "B", "weaponName": "\"Warthog\" Auto 210"}'),
    ('878318716801155233', 'ICR', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Increased Caliber Rounds", "position": "A", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'UC', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Upgraded Capacitors", "position": "B", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "C", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'HCM', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "High Capacity Magazine", "position": "A", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'RD', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Recoil Dampener", "position": "B", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'IGS', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Improved Gas System", "position": "C", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'HVR', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "High Velocity Rounds", "position": "A", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "B", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'HPB', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Hollow-Point Bullets", "position": "A", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'CB', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Conductive Bullets", "position": "B", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'HR', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Hardened Rounds", "position": "C", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'MCT', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Magazine Capacity Tweak", "position": "A", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'EA', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Electric Arc", "position": "B", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'IA', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Improved Accuracy", "position": "C", "weaponName": "\"Stubby\" Voltaic SMG"}'),
    ('878318716801155233', 'ICR', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Increased Caliber Rounds", "position": "A", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "B", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'ML', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Macro Lens", "position": "A", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'CAAO', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "CCD Array Add-On", "position": "B", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'ZL', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Zoom Lens", "position": "C", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'ECR', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Electro-Chemical Rounds", "position": "A", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'STS', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "SMRT Targeting Software", "position": "B", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'SBR', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Super Blowthrough Rounds", "position": "C", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'SSS', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Shutter Speed Sensor", "position": "A", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'AE', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Aperture Extension", "position": "B", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'EGM', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Electric Generator Mod", "position": "A", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'ULM', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Unstable Lock Mechanism", "position": "B", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'FF', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Fear Frequency", "position": "C", "weaponName": "LOK-1 Smart Rifle"}'),
    ('878318716801155233', 'FS', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Fragmentary Shell", "position": "A", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'EA', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Extra Ammo", "position": "B", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'HC', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "HE Compound", "position": "C", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'LP', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Larger Payload", "position": "B", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'IC', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Incendiary Compound", "position": "A", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'PW', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Pressure Wave", "position": "B", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'HVG', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "High Velocity Grenades", "position": "C", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'HE', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Homebrew Explosive", "position": "A", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'N+T', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Nails + Tape", "position": "B", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'CB', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Concussive Blast", "position": "C", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'PT', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Proximity Trigger", "position": "A", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'SG', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Spiky Grenade", "position": "B", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'DII', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Disabled Inertia Inhibitor", "position": "C", "weaponName": "Deepcore 40mm PGL"}'),
    ('878318716801155233', 'PPG', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Prolonged Power Generation", "position": "A", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'HCM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "High Capacity Magazine", "position": "B", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'CP', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Condensed Plasma", "position": "B", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'LNC', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Loosened Node Cohesion", "position": "C", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'QD', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Quick Deploy", "position": "A", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'ICE', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Improved Case Ejector", "position": "B", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'AB', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Armor Breaking", "position": "A", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'DFT', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Disruptive Frequency Tuning", "position": "B", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'EG', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Explosive Goodbye", "position": "A", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'PT', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Plasma Trail", "position": "B", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'TSL', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Triple Split Line", "position": "C", "weaponName": "Breach Cutter"}'),
    ('878318716801155233', 'IS', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Impact Splash", "position": "A", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'IED', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Increased Energy Density", "position": "B", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'LB', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Larger Battery", "position": "C", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'STD', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Soft Tissue Disruption", "position": "A", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'PS', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Particle Spattering", "position": "B", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'AFD', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Aluminum Foil DIY", "position": "A", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'OSB', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Open Structure Battery", "position": "B", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'HIH', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "High-Intensity Heating", "position": "A", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'NV', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Nitrogen Vaporizer", "position": "B", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'HR', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Hydrogen Rupturing", "position": "A", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'BMC', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Bio-Mass Converter", "position": "B", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'DM', 'drg-weapon-mod', '{"tier": "5", "class": "Engineer", "modName": "Dazzler Module", "position": "C", "weaponName": "Shard Diffractor"}'),
    ('878318716801155233', 'SFM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Supercharged Feed Mechanism", "position": "A", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "B", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'HCM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "High Capacity Magazine", "position": "C", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'PM', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Plastcrete MKII", "position": "A", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'RA', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Repellant Additive", "position": "B", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'DII', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Disabled Inertia Inhibitor", "position": "C", "weaponName": "Platform Gun"}'),
    ('878318716801155233', 'GS', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "Gemini System", "position": "A", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'LM', 'drg-weapon-mod', '{"tier": "1", "class": "Engineer", "modName": "LMG MKII", "position": "B", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'EAB', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Expanded Ammo Bags", "position": "A", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'QD', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Quick Deploy", "position": "B", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'WRP', 'drg-weapon-mod', '{"tier": "2", "class": "Engineer", "modName": "Widemouth Refill Port", "position": "C", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'PR', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Penetrating Rounds", "position": "A", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'Stun', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Stun", "position": "B", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'EAC', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Expanded Ammo Capacity", "position": "C", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'DS', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Defender System", "position": "A", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'HS', 'drg-weapon-mod', '{"tier": "4", "class": "Engineer", "modName": "Hawkeye System", "position": "B", "weaponName": "LMG Gun Platform"}'),
    ('878318716801155233', 'HS', 'drg-weapon-mod', '{"tier": "3", "class": "Engineer", "modName": "Hazmat System", "position": "A", "weaponName": "Engineer''s Armor"}');

-- idempotent operation, name is primary key
INSERT INTO
  public.drg_weapons_info (name, class, search_terms, mods)
VALUES
  (
    '"Warthog" Auto 210',
    'Engineer',
    null,
    '[{"name": "Supercharged Feed Mechanism", "tier": 1, "position": "A", "description": "+1 Rate of Fire"}, {"name": "Overstuffed Magazine", "tier": 1, "position": "B", "description": "+2 Magazine Size"}, {"name": "Expanded Ammo Bags", "tier": 2, "position": "A", "description": "+42 Max Ammo"}, {"name": "Loaded Shells", "tier": 2, "position": "B", "description": "+2 Pellets per Shot"}, {"name": "Choke", "tier": 2, "position": "C", "description": "x0.5 Base Spread"}, {"name": "Recoil Dampener", "tier": 3, "position": "A", "description": "x0.4 Recoil"}, {"name": "Quickfire Ejector", "tier": 3, "position": "B", "description": "-0.5sec Reload Time"}, {"name": "High Capacity Magazine", "tier": 3, "position": "C", "description": "+2 Magazine Size"}, {"name": "Tungsten Coated Buckshot", "tier": 4, "position": "A", "description": "+400% Armor Breaking"}, {"name": "Bigger Pellets", "tier": 4, "position": "B", "description": "+1 Damage per Pellet"}, {"name": "Turret Whip", "tier": 5, "position": "A", "description": "Shoot Turret to consume 5 Turret Ammo & shoot AoE Projectile; deals 160 Explosive Area Damage in 2m Radius, 100% Chance to Stun for 1.5sec, 1.0 Fear & 200% Armor Breaking w/ 3sec Cooldown"}, {"name": "Miner Adjustments", "tier": 5, "position": "B", "description": "+0.5 Rate of Fire, Automatic Fire"}]'
  ),
  (
    '"Stubby" Voltaic SMG',
    'Engineer',
    null,
    '[{"name": "Increased Caliber Rounds", "tier": 1, "position": "A", "description": "+3 Direct Damage"}, {"name": "Upgraded Capacitors", "tier": 1, "position": "B", "description": "+25% Electrocute Chance"}, {"name": "Expanded Ammo Bags", "tier": 1, "position": "C", "description": "+120 Max Ammo"}, {"name": "High Capacity Magazine", "tier": 2, "position": "A", "description": "+10 Magazine Size"}, {"name": "Recoil Dampener", "tier": 2, "position": "B", "description": "x0.7 Recoil"}, {"name": "Improved Gas System", "tier": 2, "position": "C", "description": "+3 Rate of Fire"}, {"name": "High Velocity Rounds", "tier": 3, "position": "A", "description": "+3 Direct Damage"}, {"name": "Expanded Ammo Bags", "tier": 3, "position": "B", "description": "+120 Max Ammo"}, {"name": "Hollow-Point Bullets", "tier": 4, "position": "A", "description": "+25% Weakpoint Bonus"}, {"name": "Conductive Bullets", "tier": 4, "position": "B", "description": "+25% Direct Damage to Electrocuted/IFG''d Enemies"}, {"name": "Hardened Rounds", "tier": 4, "position": "C", "description": "+250% Armor Breaking"}, {"name": "Magazine Capacity Tweak", "tier": 5, "position": "A", "description": "+20 Magazine Size"}, {"name": "Electric Arc", "tier": 5, "position": "B", "description": "+25% Chance on Electrocute to Spread Electrocute within 2.75m Radius"}, {"name": "Improved Accuracy", "tier": 5, "position": "C", "description": "x0.6 Base Spread"}]'
  ),
  (
    'LOK-1 Smart Rifle',
    'Engineer',
    array['loki', 'lok1'],
    '[{"name": "Increased Caliber Rounds", "tier": 1, "position": "A", "description": "+6 Direct Damage"}, {"name": "Expanded Ammo Bags", "tier": 1, "position": "B", "description": "+72 Max Ammo"}, {"name": "Macro Lens", "tier": 2, "position": "A", "description": "x0.2 Lock Threshold, x2 Lock-on Range"}, {"name": "CCD Array Add-On", "tier": 2, "position": "B", "description": "+1.3° Lock Threshold, x1.5 Lock Lose Threshold"}, {"name": "Zoom Lens", "tier": 2, "position": "C", "description": "+10m Lock-on Range"}, {"name": "Electro-Chemical Rounds", "tier": 3, "position": "A", "description": "+20% Damage to Electrified & Burning Targets (Stacks)"}, {"name": "SMRT Targeting Software", "tier": 3, "position": "B", "description": "Lock-on Prioritizes Low Health Enemies, Prevents Extraneous Locks based on Target Health"}, {"name": "Super Blowthrough Rounds", "tier": 3, "position": "C", "description": "+3 Penetrations"}, {"name": "Shutter Speed Sensor", "tier": 4, "position": "A", "description": "x0.85 Lock-on Time"}, {"name": "Aperture Extension", "tier": 4, "position": "B", "description": "+6 Max Lock-ons"}, {"name": "Electric Generator Mod", "tier": 5, "position": "A", "description": "First Bullet in Lock Electrocutes Targets with 3 Locks"}, {"name": "Unstable Lock Mechanism", "tier": 5, "position": "B", "description": "Full Lock adds 20% Direct Damage"}, {"name": "Fear Frequency", "tier": 5, "position": "C", "description": "Last Bullet in Burst emits Fear near Player; +0.15 Fear per Bullet; 2.4m Radius + 0.15m per Bullet"}]'
  ),
  (
    'Deepcore 40mm PGL',
    'Engineer',
    null,
    '[{"name": "Fragmentary Shell", "tier": 1, "position": "A", "description": "+1m AoE Radius"}, {"name": "Extra Ammo", "tier": 1, "position": "B", "description": "+2 Max Ammo"}, {"name": "HE Compound", "tier": 1, "position": "C", "description": "+20 Area Damage"}, {"name": "Expanded Ammo Bags", "tier": 2, "position": "A", "description": "+2 Max Ammo"}, {"name": "Larger Payload", "tier": 2, "position": "B", "description": "+20 Area Damage"}, {"name": "Incendiary Compound", "tier": 3, "position": "A", "description": "50% of Direct, Area & Armor Damage converted to Heat"}, {"name": "Pressure Wave", "tier": 3, "position": "B", "description": "+500% Armor Breaking"}, {"name": "High Velocity Grenades", "tier": 3, "position": "C", "description": "+180% Projectile Velocity"}, {"name": "Homebrew Explosive", "tier": 4, "position": "A", "description": "Damage Randomized between x0.8 - x1.4"}, {"name": "Nails + Tape", "tier": 4, "position": "B", "description": "+1m AoE Radius"}, {"name": "Concussive Blast", "tier": 4, "position": "C", "description": "+100% Chance to Stun for 3sec"}, {"name": "Proximity Trigger", "tier": 5, "position": "A", "description": "After 0.2 Arming Time, Grenades Automatically Detonate within 2m of Enemies; No Longer Detonate on Terrain Impact; Automatically Detonate after 3.3sec; x1.1 AoE Radius"}, {"name": "Spiky Grenade", "tier": 5, "position": "B", "description": "+60 Direct Damage"}, {"name": "Disabled Inertia Inhibitor", "tier": 5, "position": "C", "description": "Player''s Velocity is Added to Grenade Velocity"}]'
  ),
  (
    'Reinforced Power Drills',
    'Driller',
    null,
    '[{"name": "Barbed Drills", "tier": 1, "position": "A", "description": "+5 Damage"}, {"name": "Hardened Drill Tips", "tier": 1, "position": "B", "description": "+50% Mining Speed, +10% Movement Speed while Drilling"}, {"name": "Expanded Fuel Tanks", "tier": 1, "position": "C", "description": "+6 Max Fuel"}, {"name": "Magnetic Refrigeration", "tier": 2, "position": "A", "description": "+1 Cooling Rate"}, {"name": "Streamlined Integrity Check", "tier": 2, "position": "B", "description": "-3sec Overheat Duration"}, {"name": "Supercharged Motor", "tier": 3, "position": "A", "description": "+50% Mining Speed, +10% Movement Speed while Drilling"}, {"name": "Increased Tank Pressure", "tier": 4, "position": "A", "description": "+6 Max Fuel"}, {"name": "Bloody Cold Drills", "tier": 4, "position": "B", "description": "+1 Heat removal on Damage"}]'
  ),
  (
    'Breach Cutter',
    'Engineer',
    array['bc'],
    '[{"name": "Prolonged Power Generation", "tier": 1, "position": "A", "description": "+1.5sec Projectile Lifetime"}, {"name": "High Capacity Magazine", "tier": 1, "position": "B", "description": "+3 Magazine Size"}, {"name": "Expanded Ammo Bags", "tier": 2, "position": "A", "description": "+6 Max Ammo"}, {"name": "Condensed Plasma", "tier": 2, "position": "B", "description": "+175 Beam DPS"}, {"name": "Loosened Node Cohesion", "tier": 2, "position": "C", "description": "+3m Beam Width"}, {"name": "Quick Deploy", "tier": 3, "position": "A", "description": "-0.2sec Plasma Expansion Delay"}, {"name": "Improved Case Ejector", "tier": 3, "position": "B", "description": "-0.6sec Reload Time"}, {"name": "Armor Breaking", "tier": 4, "position": "A", "description": "+200% Armor Breaking"}, {"name": "Disruptive Frequency Tuning", "tier": 4, "position": "B", "description": "+100% Chance to Stun for 3sec"}, {"name": "Explosive Goodbye", "tier": 5, "position": "A", "description": "Manually Detonate Line, dealing 40 Explosive Area Damage in 3.5m Radius; leaves behind 3.25m Radius Plasma Sphere; deals ~35.56 Fire DPS & Slows by 20%, lasts 4.6sec"}, {"name": "Plasma Trail", "tier": 5, "position": "B", "description": "Line leaves behind Plasma field 2/3 width of Beam width; deals ~20 Fire DPS, lasts 4.6sec"}, {"name": "Triple Split Line", "tier": 5, "position": "C", "description": "Adds Line Above and Below Primary Line (does not increase DPS)"}]'
  ),
  (
    'Shard Diffractor',
    'Engineer',
    array['sd'],
    '[{"name": "Impact Splash", "tier": 1, "position": "A", "description": "+2 Area Damage"}, {"name": "Increased Energy Density", "tier": 1, "position": "B", "description": "+2 Direct Damage"}, {"name": "Larger Battery", "tier": 1, "position": "C", "description": "+100 Total Capacity"}, {"name": "Soft Tissue Disruption", "tier": 2, "position": "A", "description": "+33% Weakpoint Bonus"}, {"name": "Particle Spattering", "tier": 2, "position": "B", "description": "+0.8m AoE Radius"}, {"name": "Aluminum Foil DIY", "tier": 3, "position": "A", "description": "+50 Charge Capacity"}, {"name": "Open Structure Battery", "tier": 3, "position": "B", "description": "-0.8 Recharge Time"}, {"name": "High-Intensity Heating", "tier": 4, "position": "A", "description": "+75% Direct Damage added as Heat"}, {"name": "Nitrogen Vaporizer", "tier": 4, "position": "B", "description": "+400% Armor Breaking"}, {"name": "Hydrogen Rupturing", "tier": 5, "position": "A", "description": "+33% Area & Direct Damage against Electrocuted/IFG''d Enemies"}, {"name": "Bio-Mass Converter", "tier": 5, "position": "B", "description": "Refunds 3 Ammo to Magazine on Killing Medium-Sized or Larger Enemies; 0.25sec Cooldown"}, {"name": "Dazzler Module", "tier": 5, "position": "C", "description": "AoE Damage inflicts 80% Slow for 1sec"}]'
  ),
  (
    'Platform Gun',
    'Engineer',
    null,
    '[{"name": "Supercharged Feed Mechanism", "tier": 1, "position": "A", "description": "+1 Rate of Fire"}, {"name": "Expanded Ammo Bags", "tier": 1, "position": "B", "description": "+8 Max Ammo"}, {"name": "High Capacity Magazine", "tier": 1, "position": "C", "description": "+4 Magazine Size"}, {"name": "Plastcrete MKII", "tier": 2, "position": "A", "description": "Platforms Reduce Fall Damage"}, {"name": "Expanded Ammo Bags", "tier": 3, "position": "A", "description": "+8 Max Ammo"}, {"name": "Repellant Additive", "tier": 3, "position": "B", "description": "Enemies Attempt to Avoid Walking on Platforms"}, {"name": "Disabled Inertia Inhibitor", "tier": 3, "position": "C", "description": "Player''s Velocity is Added to Platform Velocity"}]'
  ),
  (
    'LMG Gun Platform',
    'Engineer',
    array['turret', 'turrets', 'sentry'],
    '[{"name": "Gemini System", "tier": 1, "position": "A", "description": "+1 Turret, +90 Max Ammo"}, {"name": "LMG MKII", "tier": 1, "position": "B", "description": "+2 Damage, +15 Magazine Capacity, +5m Range"}, {"name": "Expanded Ammo Bags", "tier": 2, "position": "A", "description": "+90 Max Ammo"}, {"name": "Quick Deploy", "tier": 2, "position": "B", "description": "-2sec Build Time"}, {"name": "Widemouth Refill Port", "tier": 2, "position": "C", "description": "-1sec Reload Time"}, {"name": "Penetrating Rounds", "tier": 3, "position": "A", "description": "+300% Armor Breaking"}, {"name": "Stun", "tier": 3, "position": "B", "description": "+20% Chance to Stun for 1.5sec"}, {"name": "Expanded Ammo Capacity", "tier": 3, "position": "C", "description": "+30 Magazine Capacity"}, {"name": "Defender System", "tier": 4, "position": "A", "description": "+5 Damage, Limited Scan Angle"}, {"name": "Hawkeye System", "tier": 4, "position": "B", "description": "+15m Range; Manually Aim Turret by Pinging Enemies with Laser Pointer"}]'
  ),
  (
    'Engineer''s Armor',
    'Engineer',
    null,
    '[{"name": "Hazmat System", "tier": 3, "position": "A", "description": "+50% Poison Resistance"}]'
  ),
  (
    'CRSPR Flamethrower',
    'Driller',
    array['flamer'],
    '[{"name": "High Capacity Tanks", "tier": 1, "position": "A", "description": "+25 Tank Size"}, {"name": "High Pressure Ejector", "tier": 1, "position": "B", "description": "+5m Range"}, {"name": "Unfiltered Fuel", "tier": 2, "position": "A", "description": "+4 Damage per Particle"}, {"name": "Triple Filtered Fuel", "tier": 2, "position": "B", "description": "+10 Heat per Particle"}, {"name": "Sticky Flame Duration", "tier": 2, "position": "C", "description": "+3sec Sticky Duration"}, {"name": "Oversized Valves", "tier": 3, "position": "A", "description": "+1.8 Flow Rate"}, {"name": "Sticky Flame Slowdown", "tier": 3, "position": "B", "description": "+45% Sticky Slow"}, {"name": "More Fuel", "tier": 3, "position": "C", "description": "+75 Max Fuel"}, {"name": "It Burns!", "tier": 4, "position": "A", "description": "+0.2 Fear per Particle"}, {"name": "Sticky Flame Duration", "tier": 4, "position": "B", "description": "+3sec Sticky Duration"}, {"name": "More Fuel", "tier": 4, "position": "C", "description": "+75 Max Fuel"}, {"name": "Heat Radiance", "tier": 5, "position": "A", "description": "80 Fire Damage & 80 Heat per sec within 4m while firing"}, {"name": "Targets Explode", "tier": 5, "position": "B", "description": "50% Chance on Direct Kill to Explode for 55 Fire Damage & 55 Heat within 3m"}]'
  ),
  (
    'Cryo Cannon',
    'Driller',
    array['ice'],
    '[{"name": "Larger Pressure Chamber", "tier": 1, "position": "A", "description": "x0.33 Pressure Drop Rate"}, {"name": "Faster Turbine Spinup", "tier": 1, "position": "B", "description": "-0.4sec Chargeup Time"}, {"name": "Stronger Cooling Unit", "tier": 1, "position": "C", "description": "+1 Cold per Particle"}, {"name": "Larger Reserve Tank", "tier": 2, "position": "A", "description": "+75 Tank Size"}, {"name": "Overclocked Ejection Turbine", "tier": 2, "position": "B", "description": "+5m Range"}, {"name": "Bypassed Integrity Check", "tier": 2, "position": "C", "description": "-1sec Repressurization Delay"}, {"name": "Improved Pump", "tier": 3, "position": "A", "description": "x1.75 Pressure Gain Rate"}, {"name": "Increased Flow Volume", "tier": 3, "position": "B", "description": "+1.6 Flow Rate"}, {"name": "Hard Mixture", "tier": 4, "position": "A", "description": "+3 Damage per Particle"}, {"name": "Supercooling Mixture", "tier": 4, "position": "B", "description": "+1 Cold per Particle"}, {"name": "Larger Reserve Tank", "tier": 4, "position": "C", "description": "+150 Tank Size"}, {"name": "Fragile", "tier": 5, "position": "A", "description": "Damaging Enemies below 100 HP has HP-based % chance to instantly kill"}, {"name": "Cold Radiance", "tier": 5, "position": "B", "description": "60 Cold per sec within 4m while firing"}]'
  ),
  (
    'Corrosive Sludge Pump',
    'Driller',
    null,
    '[{"name": "High Capacity Tanks", "tier": 1, "position": "A", "description": "x2 Magazine Size"}, {"name": "Better Air Pressurizer", "tier": 1, "position": "B", "description": "+40% Projectile Velocity"}, {"name": "Air Sensitive Compound", "tier": 1, "position": "C", "description": "x1.25 Puddle Width, x1.1 Puddle Height"}, {"name": "Dyse Nozzle", "tier": 2, "position": "A", "description": "+24 Charged Shot Area Damage"}, {"name": "Atomizer Nozzle", "tier": 2, "position": "B", "description": "+4 Charged Shot Fragments"}, {"name": "Potent Goo Mix", "tier": 2, "position": "C", "description": "+8 Regular Shot Area Damage"}, {"name": "Supersaturation", "tier": 3, "position": "A", "description": "x1.5 DoT Duration, x1.5 Puddle Duration"}, {"name": "More Goo Canisters", "tier": 3, "position": "B", "description": "+40 Max Ammo"}, {"name": "Spillback Extension", "tier": 4, "position": "A", "description": "-1 Ammo per Charged Shot"}, {"name": "Improved Spooling Mechanism", "tier": 4, "position": "B", "description": "x0.4 Charge Time"}, {"name": "Protein Disruption Mix", "tier": 5, "position": "A", "description": "+16.25% DoT Slow, +27.5% Puddle Slow"}, {"name": "Fluoroantimonic Acid", "tier": 5, "position": "B", "description": "+8.8 DoT DPS, +4 Puddle DPS"}]'
  ),
  (
    'Subata 120',
    'Driller',
    null,
    '[{"name": "Improved Alignment", "tier": 1, "position": "A", "description": "x0 Base Spread"}, {"name": "High Capacity Magazine", "tier": 1, "position": "B", "description": "+4 Magazine Size"}, {"name": "Expanded Ammo Bags", "tier": 2, "position": "A", "description": "+48 Max Ammo"}, {"name": "Improved Propellant", "tier": 2, "position": "B", "description": "+3 Direct Damage"}, {"name": "Recoil Compensator", "tier": 3, "position": "A", "description": "-33% Spread per Shot, x0.5 Recoil"}, {"name": "2-Round Burst", "tier": 3, "position": "B", "description": "Fires in 2-Round Bursts at 20 RoF; 2nd Bullet has 350% Armor Breaking; -0.25 Mass, -4 RoF"}, {"name": "Quickfire Ejector", "tier": 3, "position": "C", "description": "-0.6 Reload Time"}, {"name": "Hollow-Point Bullets", "tier": 4, "position": "A", "description": "+75% Weakpoint Bonus"}, {"name": "High Velocity Rounds", "tier": 4, "position": "B", "description": "+3 Direct Damage"}, {"name": "Expanded Ammo Bags", "tier": 4, "position": "C", "description": "+48 Max Ammo"}, {"name": "Volatile Bullets", "tier": 5, "position": "A", "description": "+50% Direct Damage as Fire Damage & Heat against Burning Enemies"}, {"name": "Blowthrough Rounds", "tier": 5, "position": "B", "description": "+1 Blowthrough"}, {"name": "Neuro-Corrosive Toxic Catalyst", "tier": 5, "position": "C", "description": "Additional DPS on Enemies with Corrosive, Sludge Puddle, Neurotoxin Status Effects; Killed Enemies Explode"}]'
  ),
  (
    'Experimental Plasma Charger',
    'Driller',
    array['epc'],
    '[{"name": "Increased Particle Density", "tier": 1, "position": "A", "description": "+5 Regular Shot Direct Damage"}, {"name": "Larger Battery", "tier": 1, "position": "B", "description": "+24 Battery Size"}, {"name": "Higher Charged Plasma Energy", "tier": 1, "position": "C", "description": "+15 Charged Shot Direct & Area Damage"}, {"name": "Heat Shield", "tier": 2, "position": "A", "description": "x0.4 Heat per Second When Charged"}, {"name": "Overcharged Plasma Accelerator", "tier": 2, "position": "B", "description": "+25% Regular Shot Velocity"}, {"name": "Improved Charge Efficiency", "tier": 3, "position": "A", "description": "-2 Ammo per Charged Shot"}, {"name": "Crystal Capacitors", "tier": 3, "position": "B", "description": "x2.5 Charge Speed"}, {"name": "Tweaked Radiator", "tier": 3, "position": "C", "description": "+50% Cooling Rate"}, {"name": "Expanded Plasma Splash", "tier": 4, "position": "A", "description": "+1m Charged Shot AoE Radius"}, {"name": "High Density Battery", "tier": 4, "position": "B", "description": "+24 Battery Size"}, {"name": "Reactive Shockwave", "tier": 4, "position": "C", "description": "+15 Charged Shot Direct & Area Damage"}, {"name": "Burning Nightmare", "tier": 5, "position": "A", "description": "Charged Shots penetrate enemies, no longer explode; x0.3 AoE Radius; Regular Shots deal 5+25% Direct Damage as Heat; 70% of Charged Shot Damage converted to Fire & Heat"}, {"name": "Thin Containment Field", "tier": 5, "position": "B", "description": "Shooting Charged Shot with Regular Shot causes Explosion dealing 240 Damage & 3m Terrain Carve; x0.8 Heat per Regular & Charged Shot"}, {"name": "Plasma Splash", "tier": 5, "position": "C", "description": "Regular Shots deal 10 Fire Damage (no Heat) in 1.5m Radius; -10 Direct Damage"}]'
  ),
  (
    'Colette Wave Cooker',
    'Driller',
    array['cwc'],
    '[{"name": "Convex Lens", "tier": 1, "position": "A", "description": "+2 Damage"}, {"name": "Magnetron Tube", "tier": 1, "position": "B", "description": "+100 Magazine Size"}, {"name": "Concave Lens", "tier": 1, "position": "C", "description": "x3 Shot Width"}, {"name": "Heat Sink", "tier": 2, "position": "A", "description": "-20% Heat Generation"}, {"name": "Larger Power Supply", "tier": 2, "position": "B", "description": "+2 Rate of Fire"}, {"name": "Thermoelectric Cooler", "tier": 2, "position": "C", "description": "+50% Cooling Rate, -0.5sec Overheat Duration"}, {"name": "Densification Ray", "tier": 3, "position": "A", "description": "+50% Slow on Hit for 1sec"}, {"name": "Temperature Amplifier", "tier": 3, "position": "B", "description": "*"}, {"name": "Wide Lens Add-on", "tier": 4, "position": "A", "description": "*"}, {"name": "Power Supply Overdrive", "tier": 4, "position": "B", "description": "*"}, {"name": "Contagion Transmitter", "tier": 5, "position": "A", "description": "*"}, {"name": "Boiler Ray", "tier": 5, "position": "B", "description": "+50% Chance to Explode Killed Enemies, 100 Explosive Area Damage in 2.5m Radius"}, {"name": "Exothermic Reactor", "tier": 5, "position": "C", "description": "*"}]'
  ),
  (
    'Satchel Charge',
    'Driller',
    array['c4'],
    '[{"name": "Fragmentary Shell", "tier": 1, "position": "A", "description": "+3m Damage Radius"}, {"name": "Extra Satchel Charge", "tier": 1, "position": "B", "description": "+1 Max Ammo"}, {"name": "Bigger Charge", "tier": 1, "position": "C", "description": "+250 Damage"}, {"name": "Kill Switch", "tier": 2, "position": "A", "description": "Disarm Unused Charges"}, {"name": "Extra Satchel Charge", "tier": 3, "position": "A", "description": "+1 Max Ammo"}, {"name": "Volatile Compound", "tier": 3, "position": "B", "description": "+250 Damage, Explodes upon taking Damage"}, {"name": "Big Bang", "tier": 4, "position": "A", "description": "+900% Fear Factor, +10m Fear Radius"}, {"name": "Concussive Blast", "tier": 4, "position": "B", "description": "+3.5sec Stun Duration, +10m Stun Radius"}, {"name": "Rock Mover", "tier": 4, "position": "C", "description": "+9m Carve Diameter"}]'
  ),
  (
    'Driller''s Armor',
    'Driller',
    null,
    '[{"name": "Temperature Insulation", "tier": 3, "position": "A", "description": "+50 Fire Resistance"}]'
  )
ON CONFLICT DO NOTHING;
