#!/bin/bash

# Run 'deno task test' before committing to main

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" != "main" ]; then
    exit 0
fi

# Capture the exit code of the command
OUTPUT=$(deno task test --reporter=dot 2>&1)
EXIT_CODE=$?

echo "$OUTPUT"

# prevent the commit if the command fails
if [ $EXIT_CODE -ne 0 ]; then
    echo -e "\nTESTS FAILED. COMMIT ABORTED."
    exit 1
fi
